###
GET http://localhost:4000


###
POST http://localhost:4000/api/register
Content-Type: application/json

{
    "name": "leoosathya",
    "email": "leoooosathyaaaa@gmail.com",
    "password": "Password@1098"
}


###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "leoooosathyaaaa@gmail.com",
    "password": "Password@1098"
}


### Create Note
POST http://localhost:4000/api/note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6ImhhdGlAZ21haWwuY29tIiwiaWF0IjoxNzY3ODUzMzUyLCJleHAiOjE3Njc4NTM5NTJ9.XFKOEV992_Vv8n3EkRSlbnMPHfBIdVuKeMhkvSDHkcs

{
    "title": "Hati Note 1",
    "body": "This is Hatiii's Note"
}


### Get All Notes
GET http://localhost:4000/api/note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6ImhhdGlAZ21haWwuY29tIiwiaWF0IjoxNzY3ODU2NzY2LCJleHAiOjE3Njc4NTczNjZ9.iic-fbLmkCLATJRqEFo3ehQjsDagFuPt_C3CEM3doiU


### Get All Notes with pagination
GET http://localhost:4000/api/note?skip=0&take=0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6ImhhdGlAZ21haWwuY29tIiwiaWF0IjoxNzY3ODU2NzY2LCJleHAiOjE3Njc4NTczNjZ9.iic-fbLmkCLATJRqEFo3ehQjsDagFuPt_C3CEM3doiU



### Get A Single Note 
GET http://localhost:4000/api/note/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6ImhhdGlAZ21haWwuY29tIiwiaWF0IjoxNzY3ODU5MDYzLCJleHAiOjE3Njc4NTk2NjN9.9VgQn9c2OS8PYPow6HX0I7ZYQ3lwPF2alEgFra7mNcU



### Update A Note
PATCH http://localhost:4000/api/note/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6ImhhdGlAZ21haWwuY29tIiwiaWF0IjoxNzY3ODU5MDYzLCJleHAiOjE3Njc4NTk2NjN9.9VgQn9c2OS8PYPow6HX0I7ZYQ3lwPF2alEgFra7mNcU

{
    "title": "This is Hatiii's again Updated Post No. 4"
}