###
GET http://localhost:4000


###
POST http://localhost:4000/api/register
Content-Type: application/json

{
    "name": "leoosathya",
    "email": "leoooosathyaaaa@gmail.com",
    "password": "Password@1098"
}


###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "leoooosathyaaaa@gmail.com",
    "password": "Password@1098"
}


### Create Note
POST http://localhost:4000/api/note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6Imxlb29vb3NhdGh5YWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3NjcxODQ4MzMsImV4cCI6MTc2NzE4NTQzM30.tsM8pDSO62bwnPha_6M7RGB570TNBws80hrayngnBHM

{
    "title": "Note 1",
    "body": "This is note 1"
}
